apiVersion: apps/v1
kind: Deployment
metadata:
  name: typesense-dashboard
  namespace: wordpress-help
  labels:
    app: typesense-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: typesense-dashboard
  template:
    metadata:
      labels:
        app: typesense-dashboard
    spec:
      serviceAccountName: typesense-sa
      imagePullSecrets:
      - name: github-registry-secret
      containers:
      - name: typesense-dashboard
        image: ghcr.io/amartya-dev/typesense-dashboard/typesense-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1005220000
          runAsGroup: 1005220000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-tmp
          mountPath: /tmp/nginx
        - name: nginx-run
          mountPath: /run
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      restartPolicy: Always 