name: Build Docker image and push to hub
on:
  release:
    types:
      - published
      - edited

env:
  DOCKER_IMAGE_NAME: typesense-dashboard
  DOCKER_IMAGE_VERSION: ${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: amartyag/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_VERSION }}
